# Generated by Django 5.0.1 on 2024-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customeruser_register_date_delete_selleruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='active_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد تایید'),
        ),
    ]
