# Generated by Django 5.0.1 on 2024-04-25 09:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ ساخت خبر'),
        ),
    ]
