# Generated by Django 5.0.1 on 2024-04-28 13:50

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_time',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ ساخت خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='متن خبر'),
        ),
    ]
