# Generated by Django 5.0.1 on 2024-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=250, null=True, verbose_name='واحد پول')),
                ('name', models.CharField(max_length=100, verbose_name='نام ارز دیجیتال')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل ارز دیجیتال')),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='media/symbol/', verbose_name='نماد ارز دیجیتال')),
                ('current_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='قیمت فعلی ارز')),
                ('changePrice', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True, verbose_name='تغییرات قیمت')),
            ],
            options={
                'verbose_name': 'ارز دیجیتال',
                'verbose_name_plural': 'ارز های دیجیتال',
            },
        ),
    ]
