# Generated by Django 5.0.1 on 2024-04-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcurrency',
            name='chart',
            field=models.IntegerField(default=0, verbose_name='نمودار'),
        ),
        migrations.CreateModel(
            name='CurrencyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallery/', verbose_name='عکس')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.digitalcurrency', verbose_name='ارز دیجیتال')),
            ],
        ),
        migrations.DeleteModel(
            name='CryptocurrencyPrice',
        ),
    ]
