# Generated by Django 5.0.1 on 2024-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_digitalcurrency_chart_currencygallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcurrency',
            name='symbol',
            field=models.ImageField(upload_to='media/symbol/', verbose_name='نماد ارز دیجیتال'),
        ),
        migrations.DeleteModel(
            name='CurrencyGallery',
        ),
    ]
