# Generated by Django 5.0.1 on 2024-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_digitalcurrency_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcurrency',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='media/symbol/', verbose_name='نماد ارز دیجیتال'),
        ),
    ]
