# Generated by Django 5.0.1 on 2024-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_digitalcurrency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcurrency',
            name='currency',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='digitalcurrency',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل ارز دیجیتال'),
        ),
    ]
