# Generated by Django 5.0.1 on 2024-05-12 13:36

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان تحلیل')),
                ('description', models.TextField(verbose_name='متن تحلیل')),
                ('created_time', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.digitalcurrency', verbose_name='ارز دیجیتال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل',
                'verbose_name_plural': 'تحلیل ها',
            },
        ),
    ]
