# Generated by Django 5.0.1 on 2024-05-12 13:36

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 12), verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید / عدم تایید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
            ],
            options={
                'verbose_name': 'نظرات ',
                'verbose_name_plural': 'نظرات ',
            },
        ),
    ]
